package com.example.gpa_calculatorversion1.ui

import android.content.Context
import android.content.Intent
import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.net.Uri
import android.widget.Toast
import androidx.core.content.FileProvider
import com.example.gpa_calculatorversion1.viewmodel.SemesterGroup
import java.io.File
import java.io.FileOutputStream

object ShareUtils {

    fun shareGPA(context: Context, cgpa: Double, semesters: List<SemesterGroup>) {
        val bitmap = createBitmapFromData(context, cgpa, semesters)
        if (bitmap != null) {
            shareImage(context, bitmap)
        } else {
            Toast.makeText(context, "Error creating image", Toast.LENGTH_SHORT).show()
        }
    }

    private fun createBitmapFromData(context: Context, cgpa: Double, semesters: List<SemesterGroup>): Bitmap? {
        val width = 1080
        val rowHeight = 150
        val headerHeight = 400
        val footerHeight = 100
        val height = headerHeight + (semesters.size * rowHeight) + footerHeight

        val bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888)
        val canvas = Canvas(bitmap)


        canvas.drawColor(Color.WHITE)

        val paint = Paint().apply {
            isAntiAlias = true
            textAlign = Paint.Align.CENTER
        }

        paint.color = getCGPAColor(cgpa)
        val headerRect = android.graphics.Rect(0, 0, width, headerHeight)
        canvas.drawRect(headerRect, paint)

        paint.color = Color.WHITE
        paint.textSize = 60f
        canvas.drawText("My GPA Dashboard", width / 2f, 100f, paint)

        paint.textSize = 120f
        paint.typeface = android.graphics.Typeface.DEFAULT_BOLD
        canvas.drawText(String.format("%.2f", cgpa), width / 2f, 250f, paint)

        paint.textSize = 50f
        paint.typeface = android.graphics.Typeface.DEFAULT
        canvas.drawText("Total CGPA", width / 2f, 320f, paint)


        var currentY = headerHeight + 100f
        paint.color = Color.BLACK
        paint.textAlign = Paint.Align.LEFT

        semesters.forEach { semester ->
            // Semester Name
            paint.textSize = 50f
            paint.typeface = android.graphics.Typeface.DEFAULT_BOLD
            paint.color = Color.DKGRAY
            canvas.drawText(semester.semesterName, 100f, currentY, paint)

            val gpaText = String.format("%.2f", semester.semesterGPA)
            paint.textAlign = Paint.Align.RIGHT
            paint.color = getCGPAColor(semester.semesterGPA)
            canvas.drawText(gpaText, width - 100f, currentY, paint)
            

            paint.strokeWidth = 2f
            paint.color = Color.LTGRAY
            canvas.drawLine(50f, currentY + 50f, width - 50f, currentY + 50f, paint)
            paint.textAlign = Paint.Align.LEFT

            currentY += rowHeight
        }

        paint.textAlign = Paint.Align.CENTER
        paint.textSize = 40f
        paint.color = Color.GRAY
        canvas.drawText("Generated by GPA Calculator", width / 2f, height - 50f, paint)

        return bitmap
    }

    private fun getCGPAColor(gpa: Double): Int {
        return when {
            gpa >= 3.0 -> Color.parseColor("#4CAF50") // Green
            gpa >= 2.0 -> Color.parseColor("#FFC107") // Amber
            else -> Color.parseColor("#EF5350") // Red
        }
    }

    private fun shareImage(context: Context, bitmap: Bitmap) {
        try {
            val cachePath = File(context.cacheDir, "images")
            cachePath.mkdirs()
            val stream = FileOutputStream("$cachePath/gpa_summary.png")
            bitmap.compress(Bitmap.CompressFormat.PNG, 100, stream)
            stream.close()

            val imagePath = File(context.cacheDir, "images")
            val newFile = File(imagePath, "gpa_summary.png")
            val contentUri: Uri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.provider",
                newFile
            )

            if (contentUri != null) {
                val shareIntent = Intent()
                shareIntent.action = Intent.ACTION_SEND
                shareIntent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
                shareIntent.setDataAndType(contentUri, context.contentResolver.getType(contentUri))
                shareIntent.putExtra(Intent.EXTRA_STREAM, contentUri)
                shareIntent.putExtra(Intent.EXTRA_TEXT, "Check out my GPA Summary!")
                context.startActivity(Intent.createChooser(shareIntent, "Share GPA via"))
            }

        } catch (e: Exception) {
            e.printStackTrace()
            Toast.makeText(context, "Failed to share image", Toast.LENGTH_SHORT).show()
        }
    }
}